---
- name: Provision AWS resources and deploy web server
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    desired_state: absent
  roles:
    - security-grp-setup
    - ec2-server-setup
